# Build stage
FROM node:18-alpine as builder

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm
RUN pnpm install

# Copy source code
COPY . .

# Declare build-args so Docker consumes them (eliminates the warning)
ARG CAPROVER_GIT_COMMIT_SHA
ARG VITE_API_BASE_URL
ARG VITE_UPLOADS_BASE_URL
ARG VITE_HERO_VIDEO_ENABLED
ARG VITE_HERO_VIDEO_DESKTOP
ARG VITE_HERO_VIDEO_MOBILE
ARG VITE_HERO_VIDEO_SLIDE_INDEX
ARG VITE_INTRO_POPUP_ENABLED
ARG VITE_INTRO_POPUP_DESKTOP
ARG VITE_INTRO_POPUP_MOBILE
ARG VITE_INTRO_POPUP_ONCE
ARG VITE_INTRO_POPUP_STORAGE_KEY
ARG VITE_INTRO_POPUP_DELAY_MS

# Make environment variables available to Vite at build time
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_UPLOADS_BASE_URL=$VITE_UPLOADS_BASE_URL
ENV VITE_HERO_VIDEO_ENABLED=$VITE_HERO_VIDEO_ENABLED
ENV VITE_HERO_VIDEO_DESKTOP=$VITE_HERO_VIDEO_DESKTOP
ENV VITE_HERO_VIDEO_MOBILE=$VITE_HERO_VIDEO_MOBILE
ENV VITE_HERO_VIDEO_SLIDE_INDEX=$VITE_HERO_VIDEO_SLIDE_INDEX
ENV VITE_INTRO_POPUP_ENABLED=$VITE_INTRO_POPUP_ENABLED
ENV VITE_INTRO_POPUP_DESKTOP=$VITE_INTRO_POPUP_DESKTOP
ENV VITE_INTRO_POPUP_MOBILE=$VITE_INTRO_POPUP_MOBILE
ENV VITE_INTRO_POPUP_ONCE=$VITE_INTRO_POPUP_ONCE
ENV VITE_INTRO_POPUP_STORAGE_KEY=$VITE_INTRO_POPUP_STORAGE_KEY
ENV VITE_INTRO_POPUP_DELAY_MS=$VITE_INTRO_POPUP_DELAY_MS

# Build the application
RUN pnpm build

# Production stage
FROM nginx:alpine

# Copy built files from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
